//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoConsole.Domain.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RenFilesEntities1 : DbContext
    {
        public RenFilesEntities1()
            : base("name=RenFilesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InBarcode> InBarcode { get; set; }
        public virtual DbSet<InCapture> InCapture { get; set; }
        public virtual DbSet<IntoCapture> IntoCapture { get; set; }
        public virtual DbSet<OutInfo> OutInfo { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<ForWebTest> ForWebTest { get; set; }
        public virtual DbSet<Not_inBase> Not_inBase { get; set; }
        public virtual DbSet<OutInCapture> OutInCapture { get; set; }
    }
}
