//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoConsole.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NameZip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NameZip()
        {
            this.UploadCapture = new HashSet<UploadCapture>();
        }
    
        public int Id { get; set; }
        public string NamefileZip { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadCapture> UploadCapture { get; set; }
    }
}
