//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoConsole.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutInfo
    {
        public int Id { get; set; }
        public string Barlog { get; set; }
        public string Codelog { get; set; }
        public Nullable<System.DateTime> Datelog { get; set; }
        public Nullable<bool> Renlog { get; set; }
    }
}
